### ISSUE TITLE
When I publish a new post, I need to refresh the page to see it on the timeline

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#116]
https://www.loom.com/share/c031429ed30e42d8af57aaa03f7ee88f

**Comment by mayel** [comment]
This may have to do with how I've attempted to use https://hexdocs.pm/phoenix_live_view/dom-patching.html (thinking that with infinite pagination it would be preferable to not keep the whole feed in memory). I'd like some help figuring out the issue, or otherwise we can drop temporary assigns for now.

**Comment by ivanminutillo** [comment]
For the default UI I'd take in consideration to avoid infinite scrolling and use a load more button instead. Infinite scrolling is an additive pattern and I'd like to avoid them in the default views (of course we can implement them as a config)

**Comment by mayel** [comment]
Yeah agreed, I didn't mean automatic loading of more activities, but that the 'load more' button displays X more activities below the ones already displayed rather than replacing them, or do we not want that either?
