### ISSUE TITLE
Deletion of objects/activities by the creator or admin

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#137]

**Comment by jjl** [comment]
I've started work on this and modified my local copy of `pointers`. It now in theory handles deletion how i think it should work, which is to say:

* The `pointers` table will sprout an additional deleted_at column which will initially be null.
* Added delete triggers: instead of (virtuals) and after (pointables) which set that column to `now()`.
* The record in the pointers table remains as a tombstone.
* The record in the pointable table (if it wasn't a virtual) is deleted.

But that's just at the pointers level and I'm sure you'd like to know how it should work at a bonfire level. Here's a current sketch:

* Post publishing has been moved to an epic and it seems like quite a nice way of solving some of our problems, so we will likely replicate this approach for a lot more types.
* To mirror each publish/insert epic, there will be a corresponding delete epic, which undoes the parts of the publish that we consider are useful to undo (deleting any related data that is no longer required)
* Acts should ideally be written to change their behaviour depending on the operation being performed on the relevant data
* Thus there should be a high degree of similarity between the publish and delete epics, or to paraphrase a haynes manual: "deletion is the opposite of insertion'.
* It will not be exactly 1-1, for example we would like to leave threading structure in place (+ see below about likes)
* Most of deletion is going to involve deleting mixins for the deleted things on a type-dependent basis

There are some outstanding questions, the largest of which is about how we deal with activitypub. as i remember from mumblenet, the AP adapter needs access to soft deleted data in order to do its processing. this would mean that we had to perform deletion in two stages with the second happening after the activitypub adapter has done its work.

When the team is more available, I would like to find out more about how the activitypub adapter works with regard to deletion (i have only fixed a handful of tests on the AP side of things, most of it's still a bit of a mystery). it may be that we don't actually need any data that we weren't going to leave behind anyway (e.g. threading metadata) and i'm making a problem where there isn't one. alternatively, it could be that we need to look at a new approach such as doing some of the work upfront and providing all the information needed for the actual activitypub actions in the work speicification.

the other question is about things like likes. most databases do not use tombstone records (or indeed try and use postgres as a graph database...), so they can rely on `on delete cascade` or such. we can't really.  so the question is whether we should cascade e.g. likes and follows which reference the deleted data. why do i mention this? because having created a post, someone can come along and like it, so the deletion is not quite the inverse of insertion, it needs to do more...

now, queries will doubtless be filtering out things where the other end is deleted anyway, so most of the concern i think is for the state of the database - we want to minimise the amount of unnecessary data we keep. on the other hand, this could be done by a periodic maintenance task which identifies whichever types we decide to check for and deletes any where they are referencing a deleted item. it seems likely we will ultimately need at least one such maintenance task - most systems do!

**Comment by jjl** [comment]
okay, after a chat with karen, deletion of anything except users is actually very easy on the AP side, so there aren't any problems until we get to user deletion (which i think is in the beta milestone, which is probably where it should be as it's also the most complicated deletion on the non-AP side of things)

which just leaves what do about likes, boosts etc. of the thing you're deleting.
