### ISSUE TITLE
Implement follow requests and locked accounts

### ISSUE THREAD

**Issue by KarenKonou** [bonfire-networks/bonfire-app#158]
Required for proper federation compatibility
- [x] DB schema
- [x] Context functions
- [x] Requests in notifications
- [x] LiveHandler functions
- [x] UI

**Comment by jjl** [comment]
I did the first steps to get my head around how it should work:

* [request db schema](https://github.com/bonfire-networks/bonfire_data_social/blob/main/lib/request.ex)
* [request migration](https://github.com/bonfire-networks/bonfire_social/blob/main/lib/migrations.ex)

Outstanding questions:
* How do we want to determine that the user needs to request to follow (or even not be able to even request to follow) rather than follow? Probably a mixin, maybe a verb. Not sure how much it should integrate with boundaries.
* Do we want counts for requests (for the user's own consumption)? This would require a variation of the edge count view that only takes into account requests which have not been accepted or ignored.

Notes:
* we should use the edge.table_id for the thing we want to request (in this case case, follow). this will need wrapping in the context like we do for some other things.
* I intend to leave the rest of this one to you, but holler if there's anything you can't handle (like the view if we go there)

**Comment by mayel** [comment]
Backend done: https://github.com/bonfire-networks/bonfire_social/commit/e7bd40ff4e0fe3c091c2e8f2e47f02b2dab4624d
Federation done: https://github.com/bonfire-networks/bonfire_federate_activitypub/commit/a927b8f9f54fdf1c0e28d67f515fd5cc9abdc181
Now needs some UI.

**Comment by mayel** [comment]
currently the default is to require approval for someone from a different instance following a bonfire user, since we don't set :follow to true for :guest in boundaries, but we can add an option in user settings to unlock one's profile

also I changed it so it only records the follow of a remote user once an Accept has been received, since those should be sent automatically for non-locked users as well
