### ISSUE TITLE
jungle git: dealing with branches

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#167]

**Comment by jjl** [comment]
thus far, all the git stuff in jungle has been delightfully simple. we just run some git commands to read information. if we pretend there aren't a couple of hacks right there, it's almost beautiful in its simplicity.

the problem with branches is that it involves state. in order to know what to do, we have to track some additional information and react to it appropriately.

now, things can be saved to and read from a file, this is not a big deal. the major problem is we have to figure out how to track this state in the least obtrusive way possible while being as helpful as we can. This is where it gets a bit tricky to explain, please bear with...

Let us say that you are broadly tracking main (bonfire is, after all, still working towards an alpha). You want to add a feature to a library, let's say `bonfire_social`. Without any jungle support, you would just do something like `$(cd forks/bonfire_social; git checkout -b feature/whatever)`. There probably isn't that much jungle can do to help you here.

Let's say your feature involves multiple libraries. Let's say it additional involves `bonfire_me` and you create a new branch for both of them as above. Now when we started, we had the following branches:

```
bonfire_me: main
bonfire_social: main
```

And now we have the following branches:

```
bonfire_me: feature/whatever
bonfire_social: feature/whatever
```

Presumably, when you PR these (yes, there's a separate issue for that), you're going to want to return to main, but how do we know it was main? We haven't stored it anywhere and you just ran a git command. What if it wasn't main, but was actually `release/1.0` ? you wouldn't want to return to main afterwards.

Amongst the core team, we also typically have quite a few repos checked out in the `forks` directory, so simplistic solutions like "just check it out on all repos" is not likely to be helpful. mostly it would just mean either we had empty branches lying around or i have to come up with some mechanism to prune them.

So, the simplest way of doing this would be `jungle branch feature/whatever repo_name`. I have the feeling this could get annoying when you have to make changes in quite a few repositories, as has happened from time to time.

There are additional problems with forks (is that more for the PR issue)? Inside the bonfire team, we are going to want to create branches on the repos themselves, but outsiders will not have the permission and so need to fork and then we will need to still PR against the upstream repo by default (so we have to know what it is). how can we minimise the inconvenience for people in both situations?

For short-lived things, you can probably get away with just working on main and then checking out a new branch to PR, but if it's something that's going to take longer, you probably want the branch ahead of time. if you have to pull changes from main, you probably don't want to do it all in the staging area if it's been a couple of weeks and you've made a lot of changes.

so i think the first step to all of these jungle git issues ought to be figuring out "how would we like it to look?", bearing in mind these considerations.

**Comment by mayel** [comment]
Good stuff, will share some thoughts soon. BTW there's a separate issue for forking (#176) in a later milestone.

**Comment by ivanminutillo** [comment]
not relevant anymore
