### ISSUE TITLE
 Silence a local user (instance-wide by admin) 

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#199]
Related to #198  #138 #139 #188

`extensions/bonfire_boundaries/test/object_boundaries/instance_wide_blocks/silence_actor_in_feeds_test.exs`

- [ ] data from a silenced user should be filtered out of feeds
- [ ] data from a silenced user should be filtered out of search results (with later an option to purge it)

**Comment by mayel** [comment]
Not working yet: https://github.com/bonfire-networks/bonfire_social/blob/main/test/social/boundaries/instance_wide_blocks/silence_actor_in_feeds_test.exs

**Comment by jjl** [comment]
> Not working yet: https://github.com/bonfire-networks/bonfire_social/blob/main/test/social/boundaries/instance_wide_blocks/silence_actor_in_feeds_test.exs

It's a bit confusing, but i think the problem is that you need to add every user on the instance to it. in the per user case (which passes), silencing a user encircles *the user who wants to not see the posts* so adding every user seems to be the analogue?. failing that, a combination of guest, local user and activitypub user ought to do the trick?
