### ISSUE TITLE
Improve feeds performance based on benchmark 

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#226]

**Comment by mayel** [comment]
I think it's worth opening a 1.0 milestone at this stage so we can issues like this there instead of just backlog.

**Comment by jjl** [comment]
As I understand the results, the majority of the time is taken on preloads. In particular, mixins which are not proloaded are being queried a table at a time (the default ecto behaviour).

The ultimate plan looks something like this:
* Get the database to apply the object boundary checks
* Retrieve 'fat' objects (with mixins) from a cache of some kind on the basis of returned IDs
* Fall back to the database to populate the cache

As has been joked, "cache coherence is one of the 2 hard problems in computer science: naming things, cache coherence and off by one errors". Once we support clustering, cache coherence gets "fun". It needs a lot more thought than I'm able to give it at the present time.

A more promising short term solution seems to be to write a replacement for `Repo.preload` which can batch mixins into one query. This would only be improving the most common slowdown rather than a category fix, as the ultimate solution would be, but it should be enough to bring performance back to an acceptable level for the interim, i think.
