### ISSUE TITLE
Instance-scope database-backed configuration

### ISSUE THREAD

**Issue by jjl** [bonfire-networks/bonfire-app#238]
While the current file-based mechanism makes it easy for elixir developers to customise many aspects of the bonfire install, it is not conducive to being able to edit it from within the application.

At the minute, this is primarily #214, but in the future, we will no doubt want to edit configuration from the admin panel as well

**Comment by mayel** [comment]
This has been implemented and integrated with the instance config page (though image uploads still need to be wired up):
<img width="605" alt="Screenshot 2022-04-17 at 16 59 44" src="https://user-images.githubusercontent.com/115318/163701133-69a89d7b-b7ee-4571-ab53-001d66ce82ea.png">

Instance settings are loaded from the DB on application startup and stored into Elixir's [Config](https://hexdocs.pm/elixir/Config.html), so that any code that reads that config automatically uses the correct settings without extra queries.
