### ISSUE TITLE
When a widget has no content, show an empty indication

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#289]
This is when there are no trending hashtags

![image](https://user-images.githubusercontent.com/1852065/167306625-cd417849-ffff-422a-a6f5-5b2c3c9b63bd.png)

**Comment by mayel** [comment]
Couldn't we just hide it? Which brings back my question about being able to embed a widget using something like:
```
<Bonfire.UI.Social.WidgetTagsLive 
              widget_title="Trending topics"
              current_user={current_user(assigns)}
        / >
```

instead of 
```
<Bonfire.UI.Social.WidgetLive 
              widget_title="Trending topics"
              current_user={current_user(assigns)}
            >
              <Bonfire.UI.Social.WidgetTagsLive 
                current_user={current_user(assigns)}
              />
 </Bonfire.UI.Social.WidgetLive>
```

You could still have `WidgetTagsLive` calling the `WidgetLive` component and putting its content in slots, but it hide when there's no content, and the list of widgets to show would be more easily configurable.

**Comment by ivanminutillo** [comment]
Added the empty state. I think it's good to leave it there with an indication, it would be weird if eg. admins / users add a trending topics on homepage but they do not see it because it's still empty...
