### ISSUE TITLE
When I delete a post it remains an empty activity visible in the thread page

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#317]
![image](https://user-images.githubusercontent.com/1852065/170061672-6264999e-460a-41a4-80db-cc7d8de3a8dd.png)

**Comment by mayel** [comment]
I would argue that is be expected behaviour, at least for nested posts, otherwise the nesting would change/break/become confusing. Maybe the author should not be shown, and probably some explanation should appear, such as:
<img width="565" alt="Screenshot 2022-06-05 at 09 58 10" src="https://user-images.githubusercontent.com/115318/172026779-f22266c6-5548-42a9-a77f-6c765d8e775d.png">

**Comment by mayel** [comment]
<img width="685" alt="Screenshot 2022-06-17 at 16 02 46" src="https://user-images.githubusercontent.com/115318/174222544-646ca5cc-8d64-4706-8875-42c9a500e40c.png">
