### ISSUE TITLE
Bug: duplicated boosts

### ISSUE THREAD

**Issue by dajbelshaw** [bonfire-networks/bonfire-app#393]
![Screenshot 2022-06-26 19 00 22](https://user-images.githubusercontent.com/2429426/175827718-9c7b898c-419a-4c11-bd12-1347e139a825.png)
https://playground.bonfire.cafe/post/01G6G8606GEQZX8D1GKBMB92ZX#

**Comment by mayel** [comment]
I think this is because it was re-boosted several times: https://changemap.co/bonfire/bonfire/task/6505-should-there-be-limits-on/

**Comment by mayel** [comment]
This happens when the user can't see that their boost worked so they click the button many times, other than fixing the live feedback about the boost having worked, we've discussed adding a (configurable) minimum amount of time (hours/days) allowed between re-boosts, which would prevent that (and spam/abuse at the same time).

**Comment by ivanminutillo** [comment]
fixed (we've currently limited boosting at 1)
