### ISSUE TITLE
Circles & Boundaries

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#474]
## Circle and boundaries
- [ ] #519

- [ ] #498 
- [ ] #520
- [ ] #521
    - [ ] it's not possible to switch a verb to false
    - [ ] edit button on unselected verbs dont do anything (it's also confusing which action should perform)
- [ ] Add default roles/cirlces/boundaries for admin 
- [ ] Roles should all be adjectives ![](https://i.imgur.com/yLLN8aV.png)
- [ ] I've blocked a user, but I still see in the local timeline the notification that the user followed me (prob fine)
- [ ] I receive a notification from a user that mentioned me, even if she ghosted me
- [ ] #522
```
"The function do_handle_event/3 in module Elixir.Bonfire.Boundaries.Web.CircleLive didn't receive data in a format it can recognise: \n\"** (FunctionClauseError) no function clause matching in Bonfire.Boundaries.Web.CircleLive.do_handle_event/3\"\n```\n    (bonfire_boundaries 0.1.0) lib/web/components/circles/circle_live.ex:118: Bonfire.Boundaries.Web.CircleLive.do_handle_event(\"add\", %{\"subject\" => \"01GMDXNQ8YDNGTBZBVBSRQA631\", \"value\" => \"\"}, #Phoenix.LiveView.Socket<assigns: %{__changed__: %{no_live_event_handler: true}, __context__: %{csrf_token: \"0BRfUPxLvPR0kPyEe7MOQ-2H\", current_account: %Bonfire.Data.Identity.Account{__meta__: #Ecto.Schema.Metadata<:loaded, \"bonfire_data_identity_account\">, accounted: #Ecto.Association.NotLoaded<association :accounted is not loaded>, auth_second_factor: #Ecto.Association.NotLoaded<association :auth_second_factor is not loaded>, credential: #Ecto.Association.NotLoaded<association :credential is not loaded>, email: #Ecto.Association.NotLoaded<association :email is not loaded>, id: \"01GMDXMBWT44MSGF9WGQARVAWB\", settings: nil, shared_users: #Ecto.Association.NotLoaded<association :shared_users is not loaded>, users: #Ecto.Association.NotLoaded<association :users is not loaded>}, current_account_id: \"01GMDXMBWT44MSGF9WGQARVAWB\", current_app: :bonfire_boundaries, current_extension: %{app: :bonfire_boundaries, exclude_from_nav: true, href: \"/boundaries\", icon: \"twemoji:handshake\", module: Bonfire.Boundaries.Web.BoundariesLive, name: \"Boundaries\", type: :link}, current_params: %{\"tab\" => \"ghosted\"}, current_url: \"/boundaries/ghosted\", current_user: %Bonfire.Data.Identity.User{__meta__: #Ecto.Schema.Metadata<:loaded, \"bonfire_data_identity_user\">, accounted: %Bonfire.Data.Identity.Accounted{__meta__: #Ecto.Schema.Metadata<:loaded, \"bonfire_data_identity_accounted\">, account: #Ecto.Association.NotLoaded<association :account is not loaded>, account_id: \"01GMDXMBWT44MSGF9WGQARVAWB\", id: \"01GMMQKFJ688WWM18C1TTKSFQ9\", pointer: #Ecto.Association.NotLoaded<association :pointer is not loaded>, user: #Ecto.Association.NotLoaded<association :user is not loaded>}, actor: #Ecto.Association.NotLoaded<association :actor is not loaded>, boost_activities: #Ecto.Association.NotLoaded<association :bo\n```",
```

- [x] delete a user from a boundary/circle does not update the list instantly
- [x] cannot edit a circle
- [x] invalid value for property "myself". Expected a :map, got: nil. in boundaries_live.ex

**Comment by tallship** [comment]
# The Power and Ease of Circles

## Background and History

One of the major successes of gplus during the relatively short duration of prominence it enjoyed was the feature set of *recursive* **Circles**.

This was a well known and exceedingly effective management toolset and methodology for the partitioning of *people* and other *groups* that continues to dominate the administrative functions within the information technology sector of industry.

Microsoft deployed this with local and global groups in their *Single* and *Multiple Master*  **Domain** models, and coupled with the added concepts related to *Shares* was able to expand upon similar earlier virtual topographic schemas deployed by Novell, Banyon Vines, and other forerunners of X.500 Directory Services (LDAP itself uses a subset of other X.500 based products such as DAP and NetIQ eDirectory).

The beauty of the system was in part due to *inherited* attributes of objects through ***recursion**.

Google, when it launched gplus, capitalized upon this concept of *groups* with inherited attributes by introducing this familiar schema and calling it **Circles**.

This era of social networking was barely beyond the notions of earlier relationships baked into forumware and content management systems such as vBulletin, PhpBB, PostNuke, and others, and greatly enhanced by the subsequent wave of social networking systems like MySpace and Facebook.

With respect to those latter two community based monolithic silo systems, contact object (friend) management was a tedious and laborius manually intensive process for anything beyond simple public interaction for user engagement. You could post publicly, or create a few simple group objects whereby you could place your friends, family, special interest acquaintances and then with each post you authored, select the visibility into which group is privy to view the distribution of your post.

You could indeed select multiple groups of people, but it became much more complicated when you wanted to post to say, three of those groups just to cover everyone you wanted your post available to, without avoiding the availability of other members in those gross being asked to vote your posts.

This led to the creation of more group object categories, which worked quite well, but increased the reoetitive manual manipulation of single people objects by placing them into more than one group, or having to leave people out of groups entirely and manually selecting them in an individual basis each time you published a post.

Google introduced another layer of object management called **Circles**, very much an analog to the Microsoft Domain model, which simplified and significantly reduced the the manual intervention that required much of the previous manipulation through the concepts of *recursion* and *inherited traits* by enabling the user to place entire circles within circles.

It was, at first, not well received (different terminology from "groupings"), but another strength was that it appealed to people with organizational needs and interests - just like real life relationships, and those who cussed to use the poeerful features of Circles could manipulate the dissemination of their published content in a moment or two, instead of a couple of minutes or more.

Plus, it greatly endeared people to the platform.

There were many who did not take full advantage, and this worked for them as expected in their previously comfortable, and labor intensive with flow, while many would always just set all if their posts to be available to the **"Everyone"** Circle.

Here's some examples of the power of Circles:

## Simple familial distribution of social content

* You create an empty circle and call it *family*
* you create two more circles - one called *moms-famside*, and the other *dads-famside, and you put your mom's side of the family in one and your dad's side of there can't into the other.
* you create a circle called *blacksheep*, placing family members that are the pariahs from both sides of your family.
* you create an empty circle called *friends* and then a circle called *close-friends*, and put all of your BFFs in there. Put that circle into the *friends* circle.
* you create a circle called *co-workers*, and another called *yoga-people* and populate those accordingly. Then you place those two circles into the *friends* circle.

Now you put the *moms-famside* and *dads-famside* and *blacksheep*  circles into the *family* circle.

### The Beach Barbeque

You're going to have a big beach party cookout, and you want to invite your friends and some of your family. You make an announcement and choise the following groups when you publish:

* moms-side
* blacksheep (of course, they're the fun ones)
* friends

Voila! your BFFs, close relatives (blacksheep), everyone in you're moms side of the family, your yoga classmates, and everyone you work with have been invited.

### Your Wedding Day

For this, you use the following circles

* family
* close-friends
* yoga-friends

You don't want the people you with with showing up to your wedding. But we your friends and family will receive the invitation.

But wait, you send another notice to just close-friends, yoga-friends, and blacksheep letting them know about your bachelorette party!


## Other schemas

### The College Years

You could create an empty circle called *classmates*, *math*, *chemistry*, *physics*, and *theatre*; populated those https with the members you succinate with in those classes and out those gross into the empty *classmates*  circle.


### Headhunter

You're a personal job recruiter. You fill positions with candidates for marketing, sales, payroll, Java programmers and executives. The very powerful recursion inherent in circles sites your to customize your reach with the inclusion and exclusion that you hitherto did not have.

And there's always the **everyone** group!

## Circles elsewhere

Circles are powerful, offering granular control without exceedingly repetitive manual intervention, and easy to grasp the concept of. Other projects, like "Circles" (Circuli) app and project built on top of the Matrix protocol is another Fediverse framework for simple organization of different types of people with various criteria that simplifies and partitions the personal and private aspects of your life without having to maintain separate (or, AKA 'alts') user accounts in a clean and unmessy fsshion.

Do you have people in your life that fit into more than just one circle? Not a problem, you can put people into multiple circles just fine!

**Circles** set **Bonfire** apart from other social networking, staffing above them by head and shoulders, and it's good to see this time tested, simple to use organizational publishing integration included as a core feature, unique amongst all other platforms on the ActivityPub portion of the Fediverse! 

⛵

.

**Comment by ivanminutillo** [comment]
transformed the todo list in single issues, closing this issue for now
