### ISSUE TITLE
Solve all compilation + Surface component warnings 

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#482]

**Comment by mayel** [comment]
Most of these are now gone, except for warnings in many places about remote functions being called which belong to a dependency which isn't included in that extension's dependencies, this is on purpose but those call need to be refactored to use something like `maybe_apply` so that extensions/features can be easily swapped out (and so things don't break when extensions aren't included or are disabled).

**Comment by ivanminutillo** [comment]
yeah, want to do another couple of pass to fix surface warnings
