### ISSUE TITLE
Add a setting for setting a max length in posts

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#483]
defaulting in campground to 750?

**Comment by tallship** [comment]
This is often the very first question any potential adoptee (users, server admins, and systems administrators alike) has before giving **any** social media platform serious consideration.

As for myself I searched what documentation existed on the website and after some non-trivial portion of time determined that it would be best just to review the code itself to glean this basic user-level, user-centric, UX point of interest.

One should perform a reasonable measure of due diligence in familiarizing themselves with a product prior to querying live chat systems or bug-trackers.

Similarly, one should do their best to anticipate repetitive tasks addressing such queries through proactive approaches designed to mitigate most of such time related distractions if the issue can be reduced to that if distractions. 

I do feel as if much more time was spent than should have been necessary, and as this is an important milestone goal, most welcome and a great relief, feel that it should be somehow thoughtfully and semi-prominently placed in the website (perhaps the expandable FAQ section?) where it can be easily linked whenever desired subsequent to public query.

This is part of a larger issue beyond the immediate scope of the network itself, with respect to the Fediverse at large, during the impetus for large intranetwork user migrations due to discovery processes, predominantly by newly onboarded people becoming more aware of their actual Fediverse platform options after some duration of use and participation in network activities.

The underlying motivation here is that some platforms are locked into paltry 500 character count limits for posts (notes, in ActivityPub), while others have adjustable defaults of *2000, 3000, 5000, 12,000* (some of those are 'notes', and some of those are 'articles'), and even *65535* on one particular platform instance (yes, actually of the type, 'note').

Perhaps placing the onerous for this part of the core feature set upon instance admins is the most favorable methodology, expressing maximum versatility in congruence with the ambitious goals of customization and extensibility that Bonfire very clearly is actually delivering as a welcome disruptive technology (not merely a product) - even within the ActivityPub portions of the Fediverse.

Thank you for this stated prioritization!

⛵

.

**Comment by mayel** [comment]
Done:
![Screenshot 2023-02-26 at 11 30 09](https://user-images.githubusercontent.com/115318/221382493-d0c86997-6a48-4277-8214-fbbde32038e8.png)
![Screenshot 2023-02-26 at 11 29 53](https://user-images.githubusercontent.com/115318/221382495-3b1ca9aa-f28f-4905-857f-fbca709f8e5b.png)
