### ISSUE TITLE
indicator of the selected comment does not always appear 

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#662]

**Comment by ivanminutillo** [comment]
Currently it seems to work only when visiting `/post` instead of `/discussion` and refresh the page - 
That's because it checks for: 
```"active-activity": String.contains?(@current_url || "", @permalink || "")``` and `@current_url` is always empty when navigating from feed to previewContent. When you refresh the page, the `permalink` switch from `/discussion/...` to `/post/...` indipendently from the route

**Comment by ivanminutillo** [comment]
fixed
