### ISSUE TITLE
Bug: table category_tree does not exist

### ISSUE THREAD

**Issue by lawik** [bonfire-networks/bonfire-app#844]
**Describe the bug**
After trying to get through the setup I get the localhost dev server running and it gives me an error instead of a working web app :)

**To Reproduce**

Follow introduction for Option B "easy" bare metal elixir.

Run `just dev`. Visit http://localhost:4000 and get "Something went wrong splash screen" (fully styled, nicely).

By changing logging configuration: `Logger.configure(level: :info)` in iex it was easier to isolate the thing that the request fails on:

```
[info] Sent 500 in 290ms
[error] GenServer #PID<0.1766.0> terminating
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "category_tree" does not exist
```

**Expected behavior**

**Screenshots**

**Bonfire environment (please complete the following information):**
- Running with Docker? easy
- Running env: dev
- Running version: 489f99888fa380a98f0e46d71d06ed6cba21d5ae
- Running flavour: class
- Running any extra/forked extensions: no

**Comment by mayel** [comment]
Oops this is because we recently added the `bonfire_classify` extension to `classic` but forgot to add the necessary migrations. This is precisely what we aim to solve in #243. Anyway, now added in https://github.com/bonfire-networks/bonfire-app/commit/ca41fc65124e5113202724315c10abed3dc87547 so can you please pull and try again?

**Comment by lawik** [comment]
that did it!
