### ISSUE TITLE
when trying to upload a file larger than `max_file_size`, the error message should show the max allowed file in a human readable way (eg. 10 Mb)

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#955]

**Comment by chobeat** [comment]
Hello. I'm trying to work on this. It can be assigned to me. I'm introducing the library `sizeable` and I'm also introducing some unit tests for the errors in `Bonfire.Files` that should test most error paths.

Is the error message referred to in this issue something seen by the user? If so, where? Because all the file uploads I've tried seem to return an error message without the size.

**Comment by mayel** [comment]
Thanks for taking it on :) Yeah the error message is generated here: https://github.com/bonfire-networks/bonfire_files/blob/main/lib/file_denied.ex#L16 and shown in a flash error message when you select a large image in the post composer for example.

**Comment by chobeat** [comment]
https://github.com/bonfire-networks/bonfire_files/pull/2

**Comment by mayel** [comment]
done, thanks @chobeat :)
